app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path("admin/", admin.site.urls),
    path("", include('webapp.urls')),
    path('auth/', include('accounts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views.products import ProductDetail, ProductUpdateView, \
    ProductCreateView, ProductDeleteView
from webapp.views.reviews import ReviewCreateView, ReviewDetail, \
    ReviewDeleteView, ReviewUpdateView
from webapp.views.base import IndexView, IndexRedirectView

urlpatterns =[
    path("", IndexView.as_view(), name='index'),
    path("product/", IndexRedirectView.as_view(), name='products_index_redirect'),
    path('product/add/', ProductCreateView.as_view(), name='product_add'),
    path('product/<int:pk>', ProductDetail.as_view(), name='product_detail'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/<int:pk>/confirm_delete/', ProductDeleteView.as_view(), name='confirm_delete'),
    path('review/add/<int:pk>/', ReviewCreateView.as_view(), name='add_review'),
    path('review/<int:pk>', ReviewDetail.as_view(), name='review_detail'),
    path('review/<int:pk>/update/', ReviewUpdateView.as_view(), name='review_update'),
    path('review/<int:pk>/delete/', ReviewDeleteView.as_view(), name='review_delete'),
    path('review/<int:pk>/confirm_delete/', ReviewDeleteView.as_view(), name='review_delete'),
]

webapp/models/products.py
from django.db import models
from django.utils import timezone
from django.db.models import TextChoices



class CategoryChoice(TextChoices):
    GROCERY = 'Grocery', 'Бакалея'
    BEVERAGES = 'Beverages', 'Напитки'
    HOUSEHOLD_CHEMICALS = 'Household chemicals', 'Бытовая химия'
    OTHERS = 'Others', 'Разное'


class Product(models.Model):
    name = models.CharField(
        max_length=200,
        null=False,
        blank=False,
        verbose_name="Название"
    )
    category = models.CharField(
        verbose_name='Категория',
        choices=CategoryChoice.choices,
        max_length=20,
        default=CategoryChoice.OTHERS)
    description = models.TextField(
        max_length=3000,
        null=False,
        blank=False,
        verbose_name="Текст"
    )
    pic = models.ImageField(
        null=True,
        blank=True,
        upload_to='product_pic',
        default='product_pic/placeholder.png',
        verbose_name='Картинка'
    )
    is_deleted = models.BooleanField(
        verbose_name='Удалено',
        null=False,
        default=False
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата и время создания"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата и время обновления"
    )
    deleted_at = models.DateTimeField(
        verbose_name='Дата и время удаления',
        null=True,
        default=None
    )

    def __str__(self):
        return f"{self.name} - {self.description}"

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.save()

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

webapp/models/reviews.py
from django.db import models
from django.utils import timezone
from django.db.models import TextChoices
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User



class ReviewChoice(TextChoices):
    GREAT = 5
    FINE = 4
    SATISFACTORILY = 3
    BAD = 2
    TERRIBLE = 1
    NOT_RATED = 0


class Review(models.Model):
    author = models.ForeignKey(
        to=User,
        related_name='reviews',
        on_delete=models.CASCADE,
        verbose_name='Продукт'
    )
    product = models.ForeignKey(
        'webapp.Product',
        related_name='reviews',
        on_delete=models.CASCADE,
        verbose_name='Продукт'
    )
    review = models.TextField(
        max_length=3000,
        null=False,
        blank=False,
        verbose_name="Отзыв"
    )
    rating = models.CharField(
        verbose_name='Оценка',
        choices=ReviewChoice.choices,
        max_length=20,
        null=False,
        blank=False,
        default=ReviewChoice.NOT_RATED
    )
    is_deleted = models.BooleanField(
        verbose_name='Удалено',
        null=False,
        default=False
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата и время создания"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата и время обновления"
    )
    deleted_at = models.DateTimeField(
        verbose_name='Дата и время удаления',
        null=True,
        default=None
    )

    def __str__(self):
        return f"{self.author} - {self.review}"

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.save()

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, BaseValidator
from webapp.models import Product, Review



def max_len_validator(string):
    if len(string) > 20:
        raise ValidationError('Заголовок должен быть длиннее 2 символов')
    return string


class CustomLenValidator(BaseValidator):
    def __init__(self, limit_value=200):
        message = 'Максимальная длина заголовка %(limit_value)s. Вы ввели %(show_value)s символов'
        super().__init__(limit_value=limit_value, message=message)

    def compare(self, value, limit_value):
        print(value)
        print(limit_value)
        return value > limit_value

    def clean(self, value):
        return len(value)

class ProductForm(forms.ModelForm):
    name = forms.CharField(
        validators=(MinLengthValidator(limit_value=2, message='Нужно ввести как  минимум 2 символа'), CustomLenValidator()))

    class Meta:
        model = Product
        fields = ('name', 'category', 'description', 'pic')
        labels = {
            'name': 'Название продукта',
            'category': 'Категория',
            'description': 'Описание',
            'pic': 'Картинка'
        }

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if len(name) < 2:
            raise ValidationError('Название должено быть длиннее 2 символов')
        if Product.objects.filter(name=name).exists():
            raise ValidationError('Продукт с таким название уже есть')
        return name


class SearchForm(forms.Form):
    search = forms.CharField(max_length=20, required=False, label='Найти')


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('review', 'rating')
        labels = {
            'review': 'Отзыв',
            'rating': 'Оценка'
        }

webapp/views/base.py
from django.db.models import Q
from django.utils.http import urlencode
from django.views.generic import RedirectView, ListView

from webapp.forms import SearchForm
from webapp.models import Product
from webapp.models.products import CategoryChoice


class IndexView(ListView):
    template_name = 'index.html'
    model = Product
    context_object_name = 'products'
    ordering = ('created_at',)
    paginate_by = 10
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

    def get_queryset(self):
        queryset = super().get_queryset().exclude(is_deleted=True)
        if self.search_value:
            query = Q(name__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context


class IndexRedirectView(RedirectView):
    pattern_name = 'index'

webapp/views/products.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, FormView

from webapp.forms import ProductForm
from webapp.models import Product


class GroupPermissionMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.groups.filter(name__in=['admin', 'manager']).exists()


class ProductCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    template_name = 'product_create.html'
    model = Product
    form_class = ProductForm
    success_message = 'Продукт добавлен'

    def get_success_url(self):
        return reverse('product_detail', kwargs={'pk': self.object.pk})


class ProductDetail(DetailView):
    template_name = 'product.html'
    model = Product


class ProductUpdateView(GroupPermissionMixin, LoginRequiredMixin, UpdateView):
    template_name = 'product_update.html'
    form_class = ProductForm
    model = Product
    success_message = 'Данные о продукте обновлены'
    groups = ['admin', 'manager']

    def get_success_url(self):
        return reverse('product_detail', kwargs={'pk': self.object.pk})


class ProductDeleteView(GroupPermissionMixin, SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    template_name = 'product_confirm_delete.html'
    model = Product
    success_url = reverse_lazy('index')
    success_message = 'Продукт удален'

webapp/views/reviews.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import DeleteView, CreateView, UpdateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

from webapp.models import Product, Review
from webapp.forms import ReviewForm



class ReviewCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    template_name = 'review_create.html'
    model = Review
    form_class = ReviewForm

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        form.instance.author = self.request.user
        review = form.save(commit=False)
        review.product = product
        review.save()
        return redirect('product_detail', pk=product.pk)



class ReviewDetail(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    template_name = 'review.html'
    model = Review


class ReviewUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    template_name = 'review_update.html'
    form_class = ReviewForm
    model = Review

    def get_success_url(self):
        return reverse('review_detail', kwargs={'pk': self.object.pk})


class ReviewDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    template_name = 'review_confirm_delete.html'
    model = Review
    success_url = reverse_lazy('index')

webapp/templates/article.html
{% extends 'base.html' %}
{% block title %}Article{% endblock %}
{% block menu %}
    {% if user.is_authenticated %}
        {% if perms.webapp.change_article %}
            <a href="{% url 'article_update' article.pk%}" class="btn btn-success">Update Article</a>
        {% endif %}
    <a href="{% url 'article_delete' article.pk%}" class="btn btn-danger">Delete Article</a>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Article</h1>
    <p>Title: {{ article.title }}</p>
    <p>Text: {{ article.text }}</p>
    <p>Author: {{ article.author }}</p>
    <p>Created_at: {{ article.created_at }}</p>
    <p>Status: {{ article.get_status_display}}</p>
    {% for  favorite in article.favorite_users.all %}
        <p>Пользователь <b>{{ favorite.user.username }}</b> - Заметка: {{ favorite.note }}</p>
    {% endfor %}
    </div>
{% endblock %}

webapp/templates/article_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Article confirm delete{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Вы точно хотите удалить статью?</h1>
    <p>Title: {{ article.title }}</p>
    <p>Text: {{ article.author }}</p>
        <form action="{% url 'confirm_delete' article.pk %}" method="post">
            {% csrf_token %}
            <p><input type="submit" value="Удалить"></p>
            <p><a href="{% url 'index' %}">Отмена</a></p>
        </form>
    </div>
{% endblock %}

webapp/templates/article_create.html
{% extends 'base.html' %}
{% block title %}Article Create{% endblock %}
{% block content %}
    <h1>New Article</h1>
<div class="form">
    <form action="{% url 'article_add' %}" method="post">
  {% include 'partial/article_form_2.html' with button_text='Создать' %}
    </form>
</div>
{% endblock %}

webapp/templates/article_update.html
{% extends 'base.html' %}
{% block title %}Article Create{% endblock %}
{% block content %}
    <h1>New Article</h1>
<div class="form">
    <form action="{% url 'article_update' article.pk %}" method="post">
    {% include 'partial/article_form_2.html' with button_text='Редактировать' %}
    </form>
</div>
{% endblock %}

webapp/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}Blog{% endblock %}</title>
</head>
<body>
<nav class="navbar">
    <div class="container">
        <ul class="menu">
            <li>
                <a href="{% url 'index' %}" class="btn btn-primary">Home</a>
            </li>
            {% block menu %}{% endblock %}
            {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'product_add' %}" class="btn btn-primary">Add Product</a>
                </li>
                <li>
                    <a href="{% url 'profile' user.pk %}" class="btn btn-primary">Profile</a>
                </li>
                <li>
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary" value="Выйти">
                    </form>
                </li>
                <li>Привет, {{ user.username }}</li>
            {% else %}
                 <li><a href="{% url 'login' %}" class="btn btn-primary">Войти</a></li>
                 <li><a href="{% url 'register' %}" class="btn btn-primary">Зарегистрироваться</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
</body>
</html>

webapp/templates/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}Home{% endblock %}
{% block content %}
    {% include 'partial/search.html' %}
    <h1>Products</h1>

    {% for product in products %}
    <div class="card col-8 mx-auto my-3">
            {% if product.pic %}
                <img src="/uploads/{{ product.pic }}" class="card-img-top"  alt="{{ product.name }}">
            {% else %}
                <img src="/uploads/product_pic/placeholder.png" class="card-img-top"  alt="{{ product.name }}">
            {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.description }}</p>
            <p>
                <a href="{% url 'product_detail' product.pk %}" class="card-link">Подробнее...</a>
            </p>
            {% if user.is_authenticated %}

            {% endif %}
        </div>
    </div>
  
    {% endfor %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

webapp/templates/product.html
{% extends 'base.html' %}
{% block title %}Product{% endblock %}
{% block menu %}
    {% if user.is_authenticated %}
        {% if perms.webapp.change_product %}
            <a href="{% url 'product_update' product.pk%}" class="btn btn-success">Update product</a>
            <a href="{% url 'product_delete' product.pk%}" class="btn btn-danger">Delete product</a>
            <a href="{% url 'add_review' pk=product.pk%}" class="btn btn-primary">Add review</a>
        {% endif %}
    {% endif %}
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Product</h1>
    <img src="{{ product.pic }}" alt="{{ product.name }}">
    <p>Name: {{ product.name }}</p>
    <p>Description: {{ product.description }}</p>
    <p>Category: {{ product.category}}</p>

    </div>

    <h3>Reviews:</h3>
        <div class="review-list">
            {% for review in product.reviews.all %}
            <hr>
                <div class="review">
                    <p>Автор: {{ review.author }}</p>
                    <p>Отзыв: {{ review.review }}</p>
                    <p>Оценка: {{ review.rating }}</p>
                    <p>
                        <a href="{% url 'review_detail' review.pk %}">Подробнее...</a>
                    </p>
                </div>
            <hr>
            {% empty %}
                <p>No reviews yet.</p>
            {% endfor %}
        </div>
{% endblock %}

webapp/templates/product_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Product confirm delete{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Вы точно хотите удалить статью?</h1>
    <p>Title: {{ product.name }}</p>
    <p>Text: {{ product.description }}</p>
        <form action="{% url 'confirm_delete' product.pk %}" method="post">
            {% csrf_token %}
            <p><input type="submit" value="Удалить"></p>
            <p><a href="{% url 'index' %}">Отмена</a></p>
        </form>
    </div>
{% endblock %}

webapp/templates/product_create.html
{% extends 'base.html' %}
{% block title %}Product Create{% endblock %}
{% block content %}
    <h1>New Product</h1>
<div class="form">
    <form action="{% url 'product_add' %}" method="post">
  {% include 'partial/form_2.html' with button_text='Создать' %}
    </form>
</div>
{% endblock %}

webapp/templates/product_update.html
{% extends 'base.html' %}
{% block title %}Product Create{% endblock %}
{% block content %}
    <h1>New Product</h1>
<div class="form">
    <form action="{% url 'product_update' product.pk %}" method="post">
    {% include 'partial/article_form_2.html' with button_text='Редактировать' %}
    </form>
</div>
{% endblock %}

webapp/templates/review.html
{% extends 'base.html' %}
{% block title %}Review{% endblock %}
{% block menu %}
    {% if user.is_authenticated %}
        {% if perms.webapp.change_product %}
            <a href="{% url 'review_update' review.pk%}" class="btn btn-success">Update review</a>
            <a href="{% url 'review_delete' review.pk%}" class="btn btn-danger">Delete review</a>
        {% endif %}
    {% endif %}
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Review</h1>
    <p>Автор: {{ review.author }}</p>
    <p>Отзыв: {{ review.review }}</p>
    <p>Оценка: {{ review.rating }}</p>

    </div>

{% endblock %}

webapp/templates/review_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Review confirm delete{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Вы точно хотите удалить отзыв?</h1>
    <p>Title: {{ review.review }}</p>
    <p>Text: {{ review.rate }}</p>
        <form action="{% url 'confirm_delete' review.pk %}" method="post">
            {% csrf_token %}
            <p><input type="submit" value="Удалить"></p>
            <p><a href="{% url 'index' %}">Отмена</a></p>
        </form>
    </div>
{% endblock %}

webapp/templates/review_create.html
{% extends 'base.html' %}
{% block title %}Product Create{% endblock %}
{% block content %}
    <h1>New Product</h1>
<div class="form">
    <form action="" method="post">
  {% include 'partial/form_2.html' with button_text='Создать' %}
    </form>
</div>
{% endblock %}

webapp/templates/review_update.html
{% extends 'base.html' %}
{% block title %}Review Update{% endblock %}
{% block content %}
    <h1>New Review</h1>
<div class="form">
    <form action="{% url 'review_update' review.pk %}" method="post">
    {% include 'partial/form_2.html' with button_text='Редактировать' %}
    </form>
</div>
{% endblock %}